services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: crasly-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crasly_v2:1.0
    container_name: crasly_v2-app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: crasly-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pgdata:
